"""
STEP 7 — Extract answers from AIA result PDFs.

The AIA results PDF is generated by the tool and is highly regular, which makes
extraction far safer than free-text parsing usually is:

    Algorithmic Impact Assessment Results
    Version: 1.0.1
    Section 1: Impact Level : 2
    Current Score: 56
    Raw Impact Score: 56
    Mitigation Score: 56
    ...
    Section 3.2: Impact Questions and Answers        <- raw impact questions
    16. Is the project within an area of intense public scrutiny...
    Yes [ Points: +3 ]
    ...
    Section 3.3: Mitigation Questions and Answers    <- mitigation questions
    11. Do you have documented processes in place...
    Yes [ Points: +3 ]

Four properties matter:

  * the questionnaire version is printed, so it need not be inferred
  * the scores are printed, giving an oracle to validate extraction against
  * every scored answer carries its own '[ Points: +N ]', so points come from
    the document rather than from a lookup
  * section 3.2 and 3.3 separate raw impact from mitigation explicitly

Nothing is accepted on trust. Points are summed from the extracted answers and
compared with the printed totals. A submission whose recomputed scores do not
match its printed scores is written out as failed rather than loaded, because a
plausible-looking wrong answer set is worse than a missing one.

Outputs
    data/pdf_submissions.csv   one row per PDF assessment, with validation result
    data/pdf_answers.csv       one row per extracted answer
    data/pdf_extract_review.csv  submissions that failed validation
"""
from __future__ import annotations
import re, shutil, subprocess
from collections import defaultdict
from pathlib import Path
from common import (RAW_DIR, read_csv, write_csv, fetch, absolute_url, norm,
                    similarity, impact_level, current_score, clean_version,
                    version_key, load_option_lookup, log, header)

# ---------------------------------------------------------------- patterns
RE_VERSION = re.compile(r"^\s*Version\s*:\s*v?\s*([0-9][0-9A-Za-z.]*)", re.M)
RE_LEVEL = re.compile(r"Impact\s+Level\s*:\s*(\d+)", re.I)
RE_CURRENT = re.compile(r"Current\s+Score\s*:\s*(-?\d+)", re.I)
RE_RAW = re.compile(r"Raw\s+Impact\s+Score\s*:\s*(-?\d+)", re.I)
RE_MITIGATION = re.compile(r"Mitigation\s+Score\s*:\s*(-?\d+)", re.I)

RE_PART = re.compile(r"^[ \t]*Section[ \t]+3\.(\d)[ \t]*:[ \t]*(.+?)[ \t]*$", re.M)
RE_QUESTION = re.compile(r"^\s*(\d{1,3})\.\s+(\S.*)$")
RE_POINTS = re.compile(r"\[\s*Points?\s*:\s*([+-]?\d+)\s*\]")
RE_PAGE = re.compile(r"^\s*Page \d+ of \d+\s*$", re.M)
RE_BULLET = re.compile(r"^\s*[•·▪]\s*")
RE_LEADING = re.compile(r"^[ \t]*Project Details[ \t]*$", re.M)
RE_SECTION_1 = re.compile(r"^[ \t]*Section[ \t]+1[ \t]*:", re.M)

# The block layout changed between questionnaire versions, so the point type is
# taken from the section title rather than its number:
#
#   v0.10.0   3.1 Impact Questions        3.2 Mitigation Questions
#   v1.0.1    3.1 Project Details    3.2 Impact Questions    3.3 Mitigation Questions
#
# Keying on the number instead would read a v0.10.0 impact block as project
# details and score its mitigation block as raw impact.
def part_point_type(title: str) -> str:
    t = (title or "").lower()
    if "mitigation" in t:            # checked first: some titles carry both words
        return "mitigation"
    if "impact" in t:
        return "raw"
    if "project detail" in t:
        return "none"
    return "unknown"

# A numbered line only starts a new question if its number is higher than the
# previous one. Numbered lists inside a long free-text answer restart at 1, so
# they fall below the running number and stay part of the answer where they
# belong.
#
# Gaps are allowed and expected: branching hides questions, so the printed
# numbering skips. The cap only rejects absurd jumps, since the largest section
# of the current questionnaire runs to about 107 questions. Anything this rule
# gets wrong shows up as a score mismatch against the printed totals, so the
# failure is loud rather than silent.
MAX_NUMBER_JUMP = 150


def extract_text(path: Path) -> str:
    if shutil.which("pdftotext"):
        try:
            out = subprocess.run(["pdftotext", "-layout", str(path), "-"],
                                 capture_output=True, timeout=180)
            if out.returncode == 0:
                return out.stdout.decode("utf-8", errors="replace")
        except Exception:
            pass
    try:
        from pypdf import PdfReader
        return "\n".join((p.extract_text() or "") for p in PdfReader(str(path)).pages)
    except ImportError:
        raise SystemExit("No PDF reader available. "
                         "Install poppler-utils (pdftotext) or run: pip install pypdf")
    except Exception as e:
        log(f"    ! could not read {path.name}: {e}")
        return ""


def header_values(text: str) -> dict:
    def one(rx):
        m = rx.search(text)
        return m.group(1) if m else None
    v = one(RE_VERSION)
    return {
        "stated_version": clean_version(v) if v else "",
        "stated_impact_level": int(one(RE_LEVEL)) if one(RE_LEVEL) else None,
        "stated_current": int(one(RE_CURRENT)) if one(RE_CURRENT) else None,
        "stated_raw": int(one(RE_RAW)) if one(RE_RAW) else None,
        "stated_mitigation": int(one(RE_MITIGATION)) if one(RE_MITIGATION) else None,
    }


def split_parts(text: str) -> list[tuple[str, str, str]]:
    """
    Return [(point_type, title, body)] for each questions-and-answers block.

    In the older layout the project details sit in a bare 'Project Details'
    heading before 'Section 1:', outside any Section 3.x block, so that leading
    block is picked up separately. It carries no score, but it holds the
    respondent, department and project title.
    """
    parts = []

    lead = RE_LEADING.search(text)
    if lead:
        stop = RE_SECTION_1.search(text, lead.end())
        first = RE_PART.search(text)
        end = min(x.start() for x in (stop, first) if x) if (stop or first) else len(text)
        if end > lead.end():
            parts.append(("none", "Project Details", text[lead.end():end]))

    marks = [(m.group(1), m.group(2), m.start(), m.end()) for m in RE_PART.finditer(text)]
    for i, (_num, title, _start, end) in enumerate(marks):
        stop = marks[i + 1][2] if i + 1 < len(marks) else len(text)
        parts.append((part_point_type(title), title, text[end:stop]))
    return parts


def looks_like_heading(line: str) -> bool:
    """
    A short line with no sentence punctuation is a group heading.

    Two things must not be mistaken for one: a bullet in a multi-select answer,
    and a numbered item inside a written answer. Both are short and unpunctuated
    but belong to the answer, so they are excluded explicitly.
    """
    if RE_POINTS.search(line) or RE_BULLET.match(line) or RE_QUESTION.match(line):
        return False
    return 3 < len(line) < 70 and not line.endswith((".", ":", "?", ","))


def parse_answers(body: str, point_type: str, title: str = "") -> list[dict]:
    """
    Walk a questions block, collecting numbered questions and the answer that
    follows each one.

    Two things make this harder than it looks. Questions wrap across lines, and
    the wrapped tail sits exactly where an answer would; left alone it ends up
    inside the answer, producing text like "and/or frequent litigation? No".
    And group headings sit between questions, so a free-text answer will swallow
    the next heading unless it is recognised.

    So: lines are treated as a continuation of the question until the question
    reads as complete, the answer closes as soon as a points marker is found,
    and heading-shaped lines end a written answer rather than joining it.
    """
    lines = [l.rstrip() for l in body.splitlines()]
    out, current, last_num, heading = [], None, 0, ""

    def close(entry):
        if entry is None:
            return
        answer = "\n".join(entry["_lines"]).strip()
        pts = sum(int(p) for p in RE_POINTS.findall(answer))
        clean = RE_POINTS.sub("", answer).strip()
        clean = "\n".join(RE_BULLET.sub("", l).strip() for l in clean.splitlines()).strip()
        entry["answer_text"] = clean
        entry["points"] = pts
        entry["has_points_marker"] = "Y" if RE_POINTS.search(answer) else "N"
        entry["is_free_text"] = "N" if RE_POINTS.search(answer) else "Y"
        del entry["_lines"]
        out.append(entry)

    for raw_line in lines:
        line = raw_line.strip()
        if not line or RE_PAGE.match(raw_line):
            continue

        m = RE_QUESTION.match(raw_line)
        if m:
            n = int(m.group(1))
            if last_num < n <= last_num + MAX_NUMBER_JUMP:
                close(current)
                last_num = n
                current = {
                    "part": title,
                    "point_type": point_type,
                    "heading": heading,
                    "question_number": n,
                    "question_text": m.group(2).strip(),
                    "_lines": [],
                    "_closed": False,
                }
                continue
            # a number out of sequence is body text, not a new question

        if current is None:
            if looks_like_heading(line):
                heading = line
            continue

        # The answer is already complete; anything after it belongs to the
        # document, not to this question.
        if current["_closed"]:
            if looks_like_heading(line):
                heading = line
            continue

        # Before any answer has been seen, a line continues the question while
        # the question does not yet read as finished.
        if not current["_lines"] and not RE_POINTS.search(line) \
                and not current["question_text"].endswith(("?", ":", ".")):
            current["question_text"] += " " + line
            continue

        # A heading ends a written answer rather than joining it.
        if current["_lines"] and not RE_POINTS.search(line) and looks_like_heading(line):
            heading = line
            current["_closed"] = True
            continue

        current["_lines"].append(line)

    close(current)
    return out


RE_REF = re.compile(r"\{([^}]+)\}")


def satisfies(condition: str, answers_by_field: dict) -> bool:
    """
    Whether a branching condition is met, given the answers found in the
    document. An unreadable condition counts as met, so a question is never
    dropped on a rule we could not interpret.
    """
    if not condition:
        return True

    # The published catalogs quote values with double quotes — 331 of the 332
    # conditions across all versions. Matching single quotes only made every
    # real condition unreadable, so branching never fired outside the tests.
    lit = r"""(?:'([^']*)'|"([^"]*)")"""

    def atom(expr):
        expr = expr.strip()
        m = re.match(r"^\{([^}]+)\}\s*(=|<>|!=)\s*" + lit + "$", expr)
        if m:
            got = answers_by_field.get(m.group(1).split(".")[0].strip())
            if got is None:
                return None
            value = m.group(3) if m.group(3) is not None else m.group(4)
            hit = value in got
            return hit if m.group(2) == "=" else not hit
        m = re.match(r"^\{([^}]+)\}\s+(not\s*)?contains\s+" + lit + "$", expr, re.I)
        if m:
            got = answers_by_field.get(m.group(1).split(".")[0].strip())
            if got is None:
                return None
            value = m.group(3) if m.group(3) is not None else m.group(4)
            hit = value in got
            return (not hit) if m.group(2) else hit
        m = re.match(r"^\{([^}]+)\}\s+(not)?empty$", expr, re.I)
        if m:
            got = answers_by_field.get(m.group(1).split(".")[0].strip())
            empty = not got
            return (not empty) if m.group(2) else empty
        return None

    for part in re.split(r"\s+or\s+", condition.replace("(", " ").replace(")", " "), flags=re.I):
        results = [atom(a) for a in re.split(r"\s+and\s+", part, flags=re.I)]
        if any(r is None for r in results):
            return True                      # unreadable: keep the question
        if all(results):
            return True
    return False


def apply_branching(rows, version, fields_by_name, options):
    """
    Drop answers to questions that were never asked.

    A department can answer a follow-up, then change the earlier answer that
    made it appear. The follow-up is hidden but its answer stays in the file,
    and the results document still prints it. The tool does not score it, so
    neither should we — otherwise a recomputed score comes out higher than the
    one that was published.
    """
    # what value each answered question holds, in the form conditions use
    held = {}
    for r in rows:
        fname = r.get("field_name")
        if not fname:
            continue
        opts = options.get((version, fname), [])
        text = norm(r.get("answer_text", ""))
        # An exact label match wins. Only when there is none — a checkbox
        # answer lists several labels — fall back to finding labels inside the
        # text, which would otherwise read "Not known" as also answering "No".
        vals = [o["option_value"] for o in opts
                if o.get("text_en") and norm(o["text_en"]) == text]
        if not vals:
            vals = [o["option_value"] for o in opts
                    if o.get("text_en") and norm(o["text_en"]) and norm(o["text_en"]) in text]
        held.setdefault(fname, set()).update(vals)

    dropped = 0
    for r in rows:
        fname = r.get("field_name")
        cond = fields_by_name.get(fname, {}).get("visible_if", "") if fname else ""
        r["shown"] = "Y"
        if cond and not satisfies(cond, held):
            r["shown"] = "N"
            r["hidden_by"] = cond
            if r["points"]:
                dropped += r["points"]
            r["points"] = 0
    return dropped


def main():
    header("STEP 7 — Extracting answers from AIA result PDFs")

    records = {r["og_record_id"]: r for r in read_csv("og_records.csv")}
    resources = read_csv("og_resources.csv")
    try:
        catalog = read_csv("catalog_versions.csv")
        maxima = {c["catalog_version"]: c for c in catalog}
    except SystemExit:
        maxima = {}

    qmap = defaultdict(list)
    fields_by_name = defaultdict(dict)
    try:
        for r in read_csv("question_map.csv"):
            qmap[r["catalog_version"]].append(r)
            fields_by_name[r["catalog_version"]][r["field_name"]] = r
    except SystemExit:
        log("  (question_map.csv not found — answers will not be linked to question_uid)")
    try:
        options = load_option_lookup()
    except SystemExit:
        options = {}
        log("  (option tables not found — branching cannot be applied)")

    has_json = {r["og_record_id"] for r in resources
                if r["format"] == "JSON" and r["is_assessment_artifact"] == "Y"}
    candidates = [r for r in resources
                  if r["format"] == "PDF" and r["is_assessment_artifact"] == "Y"
                  and r["language"] in ("en", "bilingual", "unknown")
                  and r["og_record_id"] not in has_json]
    # One PDF per record and submission. English is preferred, then bilingual,
    # and an unlabelled file only as a last resort: reading a French assessment
    # with English patterns produces a confident-looking wrong result.
    _rank = {"en": 0, "bilingual": 1, "unknown": 2}
    targets, seen = [], set()
    for r in sorted(candidates, key=lambda x: (x["og_record_id"], _rank.get(x["language"], 3))):
        key = (r["og_record_id"], r["submission_label"])
        if key not in seen:
            seen.add(key)
            targets.append(r)
    log(f"  PDF assessments to extract: {len(targets)}\n")

    submissions, answers, failures = [], [], []

    for res in targets:
        rec = records.get(res["og_record_id"], {})
        title = rec.get("title_en", res["resource_name"])
        name = re.sub(r"[^A-Za-z0-9._-]+", "_", res["resource_name"])[:90]
        dest = RAW_DIR / "pdf" / f"{res['og_record_id']}__{name}.pdf"
        if not dest.exists():
            try:
                dest.write_bytes(fetch(absolute_url(res["download_url"]), binary=True))
            except Exception as e:
                failures.append({"title": title, "reason": f"download failed: {e}"})
                continue

        text = extract_text(dest)
        if not text.strip():
            failures.append({"title": title,
                             "reason": "no extractable text — likely a scan, needs OCR"})
            continue

        head = header_values(text)
        parts = split_parts(text)
        if not parts:
            failures.append({"title": title,
                             "reason": "no 'Section 3.x' blocks found — unexpected layout"})
            continue

        rows = []
        for ptype, ptitle, body in parts:
            rows.extend(parse_answers(body, ptype, ptitle))
        unknown_parts = [t for pt, t, _ in parts if pt == "unknown"]

        # link answers to the catalog first, then drop the ones never asked
        pool_pre = qmap.get(head["stated_version"] or "", [])
        for r in rows:
            best, score = None, 0.0
            for q in pool_pre:
                sim = similarity(q["text_en"], r["question_text"])
                if sim > score:
                    best, score = q, sim
            r["field_name"] = best["field_name"] if (best and score >= 0.80) else ""
        dropped = apply_branching(rows, head["stated_version"] or "",
                                  fields_by_name.get(head["stated_version"] or "", {}),
                                  options)
        if dropped:
            log(f"    {dropped} point(s) excluded: answers to questions that were not asked")

        computed_raw = sum(r["points"] for r in rows if r["point_type"] == "raw")
        computed_mit = sum(r["points"] for r in rows if r["point_type"] == "mitigation")

        version = head["stated_version"] or ""
        vinfo = maxima.get(version, {})
        max_raw = float(vinfo.get("max_raw") or 0)
        max_mit = float(vinfo.get("max_mitigation") or 0)
        computed_cur, reduced = current_score(computed_raw, computed_mit, max_mit)
        pct = round(computed_cur / max_raw * 100, 1) if max_raw else None

        raw_ok = head["stated_raw"] is not None and computed_raw == head["stated_raw"]
        mit_ok = head["stated_mitigation"] is not None and computed_mit == head["stated_mitigation"]
        cur_ok = head["stated_current"] is None or computed_cur == head["stated_current"]
        lvl_ok = head["stated_impact_level"] is None or impact_level(pct) == head["stated_impact_level"]
        validated = raw_ok and mit_ok and cur_ok

        # link answers to the catalog where we can
        pool = qmap.get(version, [])
        for r in rows:
            best, score = None, 0.0
            for q in pool:
                s = similarity(q["text_en"], r["question_text"])
                if s > score:
                    best, score = q, s
            r["question_uid"] = best["question_uid"] if (best and score >= 0.80) else ""
            r["match_score"] = round(score, 3)

        submissions.append({
            "og_record_id": res["og_record_id"],
            "title": title,
            "department": rec.get("department", ""),
            "submission_label": res["submission_label"],
            "catalog_version": version,
            "version_source": "stated_in_pdf" if version else "unknown",
            "publication_date": rec.get("record_released", ""),
            "stated_raw": head["stated_raw"],
            "stated_mitigation": head["stated_mitigation"],
            "stated_current": head["stated_current"],
            "stated_impact_level": head["stated_impact_level"],
            "computed_raw": computed_raw,
            "computed_mitigation": computed_mit,
            "computed_current": computed_cur,
            "computed_impact_level": impact_level(pct),
            "current_score_pct": pct,
            "reduction_applied": "Y" if reduced else "N",
            "raw_matches": "Y" if raw_ok else "N",
            "mitigation_matches": "Y" if mit_ok else "N",
            "current_matches": "Y" if cur_ok else "N",
            "level_matches": "Y" if lvl_ok else "N",
            "validated": "Y" if validated else "N",
            "answer_count": len(rows),
            "linked_to_catalog": sum(1 for r in rows if r["question_uid"]),
            "unclassified_sections": "; ".join(unknown_parts),
            "source_format": "PDF",
            "source_file": dest.name,
            "extraction_method": "pdf_text",
        })

        for r in rows:
            answers.append({
                "og_record_id": res["og_record_id"],
                "submission_label": res["submission_label"],
                "catalog_version": version,
                "validated": "Y" if validated else "N",
                **r,
            })

        flag = "validated" if validated else "MISMATCH"
        log(f"  {title[:40]:<42} v{version or '?':<7} "
            f"raw {computed_raw}/{head['stated_raw']}  "
            f"mit {computed_mit}/{head['stated_mitigation']}  "
            f"{len(rows)} answers  [{flag}]")
        if not validated:
            failures.append({
                "title": title,
                "reason": f"recomputed raw {computed_raw} vs printed {head['stated_raw']}; "
                          f"recomputed mitigation {computed_mit} vs printed {head['stated_mitigation']}",
            })

    write_csv("pdf_submissions.csv", submissions)
    write_csv("pdf_answers.csv", answers)
    write_csv("pdf_extract_review.csv", failures)

    header("SUMMARY")
    ok = [s for s in submissions if s["validated"] == "Y"]
    log(f"  PDFs processed        : {len(submissions)}")
    log(f"  scores reproduced     : {len(ok)}")
    log(f"  needing review        : {len(submissions) - len(ok) + len(failures) - (len(submissions) - len(ok))}")
    log(f"  answers extracted     : {len(answers)}")
    if submissions:
        linked = sum(s["linked_to_catalog"] for s in submissions)
        total = sum(s["answer_count"] for s in submissions)
        log(f"  answers linked to catalog: {linked} of {total}")
    if failures:
        log("\n  Review these before loading:")
        for f in failures:
            log(f"    - {f['title'][:46]}: {f['reason']}")
    log("\n  Only rows with validated = Y should be merged into the master table.")
    log("  A recomputed score that matches the printed score means every scored")
    log("  answer was found; a mismatch means at least one was missed.")


if __name__ == "__main__":
    main()
